#Ubidots Log
"""
UBIDOTS_TOKEN = 'BBFF-HHmBlj5C4CVgIrlBjgakdtyeFsYx1p' 
UBIDOTS_API_KEY='BBFF-7bacbcf068b323745bbdb16423f195797bb'
UBIDOTS_NAME_DEVICE ='Prueba' 
"""

UBIDOTS_TOKEN = 'BBFF-IH5I4OcjNkdFY6IAcKjnBhbdEThV8j' 
UBIDOTS_API_KEY='BBFF-e95568780d8217c718fac68bf30c60c2c30'
#DEVICES
UBIDOTS_POZO_1='POZO_PRUEBA_1'
UBIDOTS_POZO_2='POZO_PRUEBA_2'
UBIDOTS_POZO_3='POZO_PRUEBA_3'
UBIDOTS_TEMPERATURAS='TEMPERATURAS'

#POZO 1
UBIDOTS_POZO_1_NiVEL_1="nivel_1"
UBIDOTS_POZO_1_PRESION_1="presion_1"
UBIDOTS_POZO_1_CAUDAL_1="caudal_1"
POZO_1_MEDIDA_NIVEL_1=50
POZO_1_INSTALACION_NIVEL_1=50
POZO_1_PRESION_1=10
POZO_1_LP_CAUDAL_1=100


#POZO2
UBIDOTS_POZO_2_NiVEL_1="nivel_1"
UBIDOTS_POZO_2_PRESION_1="presion_1"
UBIDOTS_POZO_2_CAUDAL_1="caudal_1"
POZO_2_MEDIDA_NIVEL_1=50
POZO_2_INSTALACION_NIVEL_1=50
POZO_2_PRESION_1=10
POZO_2_LP_CAUDAL_1=100

#POZO3
UBIDOTS_POZO_3_NiVEL_1="nivel_1"
UBIDOTS_POZO_3_PRESION_1="presion_1"
UBIDOTS_POZO_3_PRESION_2="presion_2"
UBIDOTS_POZO_3_CAUDAL_1="caudal_1"
UBIDOTS_POZO_3_CAUDAL_2="caudal_2"
POZO_3_MEDIDA_NIVEL_1=50
POZO_3_INSTALACION_NIVEL_1=50
POZO_3_PRESION_1=10
POZO_3_PRESION_2=10
POZO_3_LP_CAUDAL_1=100
POZO_3_LP_CAUDAL_2=100

#TEMPERATURAS
UBIDOTS_TEMPERATURA_1="temperatura_1"
UBIDOTS_TEMPERATURA_2="temperatura_2"
UBIDOTS_TEMPERATURA_3="temperatura_3"

#URIS
URI_CREAR_TOKEN='https://industrial.api.ubidots.com/api/v1.6/auth/token/'
URI_DEVICE='https://industrial.api.ubidots.com/api/v1.6/devices/'




VARS_POZO_1={
            UBIDOTS_POZO_1_NiVEL_1,
            UBIDOTS_POZO_1_PRESION_1,
            UBIDOTS_POZO_1_CAUDAL_1,

            }

VARS_POZO_2={
            UBIDOTS_POZO_2_NiVEL_1,
            UBIDOTS_POZO_2_PRESION_1,
            UBIDOTS_POZO_2_CAUDAL_1,

            }
VARS_POZO_3={
            UBIDOTS_POZO_3_NiVEL_1,
            UBIDOTS_POZO_3_PRESION_1,
            UBIDOTS_POZO_3_PRESION_2,
            UBIDOTS_POZO_3_CAUDAL_1,
            UBIDOTS_POZO_3_CAUDAL_2,

            }
VARS_TEMPERATURAS_={
                    UBIDOTS_TEMPERATURA_1,
                    UBIDOTS_TEMPERATURA_2,
                    UBIDOTS_TEMPERATURA_3,

                    }

VARS_DEVICES={
             UBIDOTS_POZO_1,
             UBIDOTS_POZO_2,
             UBIDOTS_POZO_3,
             UBIDOTS_TEMPERATURAS
             }
